name: IDSL_MINT

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.9
  - rdkit
  - pathlib>=1.0.1
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - torch>=2.0
  - torchinfo>=1.8.0
  - tqdm>=4.45.0
  - PyYAML
  - joblib
  - pandas
  - openpyxl
  - pip:
    - typed-argument-parser>=1.6.1
    - git+https://github.com/idslme/IDSL_MINT
